# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "tiny_tds"
gem 'json'
gem 'debugger'

#gem 'odf-report'
#gem 'odf-report', :git => 'https://github.com/railty/odf-report.git'
gem 'json-odf-report', :path =>'../'


